import { app, BrowserWindow, ipcMain, dialog } from 'electron';
import db from './db'; // Initialize the database
import fs from 'fs';
import path from 'path';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

ipcMain.handle('dialog:openFolder', async () => {
  const { canceled, filePaths } = await dialog.showOpenDialog({
    properties: ['openDirectory'],
  });
  if (canceled) {
    return;
  } else {
    return filePaths[0];
  }
});

ipcMain.handle('db:addFolder', (event, folderPath) => {
  const stmt = db.prepare('INSERT INTO folders (path, collection_id) VALUES (?, ?)');
  stmt.run(folderPath, 1); // Assuming a default collection_id of 1 for now
});

ipcMain.handle('db:getFolders', () => {
  const stmt = db.prepare('SELECT id, path FROM folders');
  return stmt.all();
});

ipcMain.handle('db:removeFolder', (event, folderId) => {
  const stmt = db.prepare('DELETE FROM folders WHERE id = ?');
  stmt.run(folderId);
});

ipcMain.handle('db:getImages', () => {
  const stmt = db.prepare('SELECT path FROM folders');
  const folders = stmt.all() as { path: string }[];
  const imagePaths: string[] = [];

  for (const folder of folders) {
    const files = fs.readdirSync(folder.path);
    for (const file of files) {
      const extension = path.extname(file).toLowerCase();
      if (['.jpg', '.jpeg', '.png', '.webp'].includes(extension)) {
        imagePaths.push(path.join(folder.path, file));
      }
    }
  }

  return imagePaths;
});

ipcMain.handle('db:getImage', (event, imagePath) => {
  let stmt = db.prepare('SELECT * FROM images WHERE path = ?');
  let image = stmt.get(imagePath);

  if (!image) {
    stmt = db.prepare('INSERT INTO images (path, collection_id) VALUES (?, ?)');
    const result = stmt.run(imagePath, 1); // Assuming a default collection_id of 1
    image = { id: result.lastInsertRowid, path: imagePath, description: null, is_favorite: 0, collection_id: 1 };
  }

  return image;
});

ipcMain.handle('db:updateImageDescription', (event, imagePath, description) => {
  const stmt = db.prepare('UPDATE images SET description = ? WHERE path = ?');
  stmt.run(description, imagePath);
});
